version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue3_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      VUE_APP_API_URL: "http://localhost:8000"

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
